/* All artwork and exercises are local. A seed keeps screen, solutions and print in sync. */
'use strict';
const names = ['Alex','Mika','Lena','Noah','Samira','Emil','Mara','Jona','Elif','Robin','Nora','Theo'];
const colors = [{name:'blau',hex:'#5486b5'},{name:'grün',hex:'#6b956b'},{name:'rot',hex:'#c56b60'},{name:'gelb',hex:'#e7bc52'}];
const hairColors = [{name:'braun',hex:'#71503a'},{name:'blond',hex:'#dfbd70'},{name:'schwarz',hex:'#303338'},{name:'rotbraun',hex:'#ab603b'}];
function random(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function makePerson(seed){const r=random(seed),pick=a=>a[Math.floor(r()*a.length)];return {seed,name:pick(names),age:10+Math.floor(r()*4),height:140+Math.floor(r()*23),hair:pick(hairColors),style:pick(['kurz','schulterlang','lockig']),face:pick(['oval','rund']),shirt:pick(colors),pattern:pick(['gestreift','gepunktet']),glasses:r()>.5,freckles:r()>.5,skin:pick(['#f3d2b6','#d8a47f','#aa7355']),build:pick(['schmal','kräftig']),bag:r()>.5};}
function newSeed(){return crypto.getRandomValues(new Uint32Array(1))[0];}
const initialSeed=new URLSearchParams(location.search).get('person');
let person=makePerson(/^\d{1,10}$/.test(initialSeed||'')?Number(initialSeed)>>>0:newSeed());
let active=0;
const stationNames=['1 · Hinschauen','2 · Wörter finden','3 · Ordnen','4 · Formulieren','5 · Textdetektiv','Schreibblatt','Lösungen'];
let illustrationId=0;
function art(p){
 const patternId=`pattern-${p.seed}-${++illustrationId}`;
 const width=p.build==='kräftig'?50:41;
 const hairBack=p.style==='schulterlang'?`<path d="M78 78 Q72 19 120 23 Q167 23 164 83 L172 150 L69 150Z" fill="${p.hair.hex}"/>`:'';
 const hair=p.style==='lockig'?Array.from({length:9},(_,i)=>`<circle cx="${79+i*10}" cy="${47-Math.sin(i/8*Math.PI)*18}" r="14" fill="${p.hair.hex}"/>`).join(''):`<path d="M79 64 Q73 22 117 25 Q165 19 162 66 Q145 55 139 39 Q114 63 79 64Z" fill="${p.hair.hex}"/>`;
 const pattern=p.pattern==='gestreift'?'<path d="M0 5H12" stroke="#303d3b" stroke-width="2"/>':'<circle cx="5" cy="5" r="2" fill="#303d3b"/>';
 return `<svg class="person-art" viewBox="0 0 240 390" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Gezeichnete Person als Vorlage für die Beschreibung"><defs><pattern id="${patternId}" width="12" height="12" patternUnits="userSpaceOnUse">${pattern}</pattern></defs><g stroke="#303d3b" stroke-width="2" stroke-linejoin="round">${hairBack}<path d="M91 239 L116 238 L115 350 L88 350Z M124 238 L151 239 L155 350 L127 350Z" fill="#d9dce0"/><path d="M87 345H115V366H70Q66 351 87 345 M127 345H155L170 361V366H127Z" fill="#fafafa"/><path d="M${120-width} 142 L${108-width} 226 Q${109-width} 244 ${121-width} 240 L${135-width} 169 M${120+width} 142 L${132+width} 226 Q${131+width} 244 ${119+width} 240 L${105+width} 169" fill="${p.skin}"/><path d="M108 108V136H132V108" fill="${p.skin}"/><path d="M108 129 L${120-width} 140 L${107-width} 180 L${125-width} 188 L${128-width} 239 H${112+width} L${115+width} 188 L${133+width} 180 L${120+width} 140 L132 129 Q120 148 108 129Z" fill="${p.shirt.hex}"/><path d="M108 129 L${120-width} 140 L${107-width} 180 L${125-width} 188 L${128-width} 239 H${112+width} L${115+width} 188 L${133+width} 180 L${120+width} 140 L132 129 Q120 148 108 129Z" fill="url(#${patternId})"/><ellipse cx="79" cy="79" rx="7" ry="11" fill="${p.skin}"/><ellipse cx="161" cy="79" rx="7" ry="11" fill="${p.skin}"/><ellipse cx="120" cy="77" rx="${p.face==='rund'?42:35}" ry="45" fill="${p.skin}"/>${hair}<path d="M96 67L107 65 M134 65L145 67" fill="none"/><circle cx="103" cy="77" r="3"/><circle cx="137" cy="77" r="3"/><path d="M119 79L115 92H122 M108 102Q120 110 132 102" fill="none"/>${p.freckles?'<g fill="#825239" stroke="none"><circle cx="95" cy="90" r="1.8"/><circle cx="102" cy="93" r="1.8"/><circle cx="97" cy="97" r="1.8"/><circle cx="142" cy="91" r="1.8"/><circle cx="148" cy="95" r="1.8"/><circle cx="140" cy="97" r="1.8"/></g>':''}${p.glasses?'<g fill="none" stroke-width="3"><rect x="88" y="68" width="27" height="20" rx="7"/><rect x="125" y="68" width="27" height="20" rx="7"/><path d="M115 75H125 M80 73L88 75 M152 75L161 73"/></g>':''}${p.bag?'<path d="M87 140L159 226" fill="none" stroke="#795e45" stroke-width="8"/><rect x="144" y="211" width="37" height="45" rx="5" fill="#c8ab83"/><path d="M145 224H180"/>':''}</g></svg>`;
}
function lines(n=2){return `<div class="lines ${n>4?'large':n===1?'short':''}">${'<span></span>'.repeat(n)}</div>`;}
function head(title,id){return `<div class="sheet-head"><span>Deutsch · 5. Schulstufe</span><span>Personenbeschreibung · Vorlage ${person.seed}</span></div><h2>${title}</h2><div class="name-line">Name: ____________________________ Klasse: ______ Datum: __________</div>`;}
function card(p){return `<div class="portrait-layout">${art(p)}<div class="person-card"><span class="tag">Deine Schreibvorlage</span><h3>${p.name}</h3><div class="facts"><span>${p.age} Jahre</span><span>${p.height} cm groß</span></div><p>Beschreibe so genau, dass jemand die Person wiedererkennen kann.</p><p class="small">Alle Figuren sind erfunden. Name, Alter und Größe stehen fest. Weitere Angaben entnimmst du dem Bild.</p><p class="print-only">Farbangaben für Schwarz-Weiß-Kopien: Haare ${p.hair.name}; T-Shirt ${p.shirt.name}; Hose grau; Schuhe weiß.</p></div></div>`;}
function quiz(id,q,options,correct,why){return `<fieldset data-answer="${correct}"><legend>${q}</legend><div class="choices">${options.map((o,i)=>`<button class="choice" data-choice="${i}" aria-describedby="feedback-${id}">${o}</button>`).join('')}</div><div class="print-only print-choices">${options.map(o=>'□ '+o).join(' &nbsp; ')}</div><p class="feedback" id="feedback-${id}" data-explanation="${why}" role="status"></p></fieldset>`;}
function observation(){return `${head('1 · Genau hinschauen')}${card(person)}<p>Betrachte die Figur genau. Kreuze jeweils eine Antwort an.</p>${quiz('pattern','Welches Muster hat das T-Shirt?',['gestreift','gepunktet'],person.pattern==='gestreift'?0:1,'Achte auf Linien oder kleine Punkte auf dem Stoff.')}${quiz('glasses','Die Person trägt eine Brille.',['richtig','falsch'],person.glasses?0:1,'Prüfe, ob vor den Augen ein Brillengestell zu sehen ist.')}${quiz('fact','Was kannst du allein aus dem Bild sicher erkennen?',['Die Person ist hilfsbereit.','Die Person trägt eine lange Hose.'],1,'Eine Hose ist sichtbar. Hilfsbereitschaft erkennt man am Verhalten, nicht am Aussehen.')}<div class="task"><strong>Finde zwei weitere sichtbare Merkmale.</strong>${lines(2)}</div>`;}
function vocabulary(){return `${head('2 · Treffende Wörter finden')}<p>Genau passende Wörter machen eine Beschreibung anschaulich.</p><div class="wordbank help">Wortschatz: oval · rund · schulterlang · lockig · glatt · schmal · kräftig · gestreift · gepunktet · Sommersprossen</div>${quiz('word1','Welche Wortgruppe beschreibt die Haarlänge?',['schulterlange Haare','dunkle Haare','lockige Haare'],0,'„Schulterlang“ beschreibt die Länge; „dunkel“ die Farbe und „lockig“ die Form.')}${quiz('word2','Welches Wort ist das Gegenteil von „glatt“ bei Haaren?',['blond','lockig','kurz'],1,'Glatt und lockig beschreiben unterschiedliche Haarformen.')}${quiz('word3','Welche Beschreibung ist am genauesten?',['eine schöne Kleidung','ein Oberteil','ein blaues, gestreiftes T-Shirt'],2,'Kleidungsstück, Farbe und Muster liefern konkrete Informationen.')}<div class="task"><strong>Ergänze jeweils zwei passende Adjektive.</strong><p>Ein __________________, __________________ Gesicht.</p><p>__________________, __________________ Haare.</p><p>Ein __________________, __________________ Pullover.</p></div><div class="task"><strong>Beschreibe drei Merkmale deiner Figur in Wortgruppen.</strong><p class="small">Beispiel: kurze, braune Haare. Schau dafür auf Station 1.</p>${lines(3)}</div>`;}
const groups=['Name / Alter','Körperbau','Gesicht / Haare','Kleidung','Besonderheiten'];
const sorting=[['elf Jahre',0],['schmale Schultern',1],['ovales Gesicht',2],['gestreiftes T-Shirt',3],['runde Brille',4],['lockige Haare',2]];
function ordering(){return `${head('3 · Ordnung schaffen')}<p>Ordne die Merkmale zu. Auf Papier: Schreibe den passenden Buchstaben dazu.</p><div class="wordbank">${groups.map((g,i)=>`${'ABCDE'[i]}: ${g}`).join(' · ')}</div><div class="sorting">${sorting.map(([s,a],i)=>`<label>${s}<select class="screen-only sort-answer" data-answer="${a}" aria-label="Kategorie für ${s}"><option value="">Bitte wählen</option>${groups.map((g,j)=>`<option value="${j}">${g}</option>`).join('')}</select><span class="print-only">_____</span></label>`).join('')}</div><button class="screen-only" id="check-sorting">Zuordnung prüfen</button><p id="sorting-feedback" class="feedback" role="status"></p><div class="task"><strong>Bringe den Schreibplan in eine sinnvolle Reihenfolge.</strong><p>Nummeriere von 1 bis 5.</p><ol class="order-list" style="list-style:none"><li>___ Kleidung und Eindruck</li><li>___ Name und Alter</li><li>___ Auffällige Besonderheiten</li><li>___ Haare und Gesicht</li><li>___ Größe und Körperbau</li></ol><details><summary>Reihenfolge prüfen</summary><p>Von oben nach unten: 4, 1, 5, 3, 2.</p></details></div><div class="hint help">Dein Schreibplan: Name und Alter → Größe und Körperbau → Haare und Gesicht → Kleidung und Eindruck → Besonderheiten.</div><div class="task"><strong>Warum hilft diese Reihenfolge beim Lesen?</strong>${lines(2)}</div>`;}
function phrasing(){return `<h2>4 · Besser formulieren</h2><p>Verbessere die Sätze. Erhalte die Informationen und vermeide Wiederholungen.</p><div class="quote">Alex hat braune Haare. Alex hat kurze Haare. Alex hat eine Brille.</div><div class="help wordbank">Satzanfänge: Die Person … · Auffällig ist … · Zum T-Shirt trägt … · Im Gesicht …</div>${lines(2)}<details><summary>Mögliche Verbesserung</summary><p>Alex hat kurze, braune Haare. Auffällig ist die Brille.</p></details>${quiz('tense','Welcher Satz beschreibt die Person in der Gegenwart?',['Mika trug eine graue Hose.','Mika trägt eine graue Hose.'],1,'„Trägt“ steht im Präsens. Nutze für diese Übung die Gegenwart.')}`;}
function detective(){return `<h2>5 · Textdetektiv</h2><p>Für diese Aufgabe gelten folgende Angaben: Nora, 11 Jahre, 148 cm, eine Brille, glatte Haare und ein gepunktetes T-Shirt. Finde und verbessere <strong>vier Stellen</strong>.</p><div class="quote">Nora ist zwölf Jahre alt und 148 cm groß. Die Haare sind lockig. Nora trägt ein gestreiftes T-Shirt und eine Brille. Nora ist bestimmt immer gemein, weil sie eine Brille trägt.</div>${lines(3)}<details><summary>Fehler und Begründungen</summary><p>Elf statt zwölf Jahre; glatt statt lockig; gepunktet statt gestreift. Die Behauptung „gemein“ ist unbegründet: Eine Brille sagt nichts über den Charakter aus.</p></details>`;}
function writingFront(p=person){return `${head('Schreibwerkstatt · Erst planen')}${card(p)}<div class="hint"><strong>Dein Auftrag:</strong> Beschreibe ${p.name} mit etwa <strong>100 Wörtern</strong>. Schreibe einen zusammenhängenden Text in der Gegenwart. Nutze die Rückseite. Beschreibe sichtbare Merkmale und erfinde keine Charaktereigenschaften.</div><h3>Meine Stichwörter</h3><div class="plan">${['Name, Alter, Größe','Körperbau','Haare und Gesicht','Kleidung','Besonderheiten','Eindruck: „wirkt …“'].map(s=>`<div><strong>${s}</strong>${lines(1)}</div>`).join('')}</div><div class="wordbank help small">Wörter als Hilfe: rund / oval · kurz / schulterlang / lockig · schmal / kräftig · gestreift / gepunktet · Brille · Sommersprossen · Umhängetasche</div>`;}
function writingBack(){return `${head('Schreibwerkstatt · Schreiben & prüfen')}<p><strong>Meine Personenbeschreibung · etwa 100 Wörter</strong></p>${lines(13)}<h3>Mein letzter Check</h3><ul class="checklist"><li>Meine Beschreibung hat eine sinnvolle Reihenfolge.</li><li>Meine Angaben stimmen mit Bild und Infokarte überein.</li><li>Ich beschreibe Haare, Gesicht, Kleidung und Besonderheiten genau.</li><li>Ich verwende passende Adjektive und verschiedene Satzanfänge.</li><li>Ich kennzeichne einen Eindruck mit „wirkt“ oder „scheint“.</li><li>Ich habe etwa 100 Wörter geschrieben und meinen Text zweimal geprüft.</li></ul><p class="small">Prüfe beim zweiten Lesen besonders Satzanfänge, Satzzeichen und die Schreibung der Wörter.</p>`;}
function sample(p){return `Ich beschreibe ${p.name}. Die Person ist ${p.age} Jahre alt und ${p.height} Zentimeter groß. Der Körperbau ist ${p.build}. Das Gesicht ist ${p.face}. Die Haare sind ${p.hair.name} und ${p.style}. Über den Augen sieht man zwei Augenbrauen. Unter der Nase ist ein lächelnder Mund zu erkennen. ${p.glasses?'Vor den Augen sitzt eine Brille.':'Die Person trägt keine Brille.'} ${p.freckles?'Auf den Wangen fallen kleine Sommersprossen auf.':'Die Wangen haben keine Sommersprossen.'} Das T-Shirt ist ${p.shirt.name} und ${p.pattern}. Das Oberteil hat kurze Ärmel, sodass die Unterarme und die Hände gut zu sehen sind. Dazu trägt ${p.name} eine lange, graue Hose und weiße Schuhe. ${p.bag?'Eine Umhängetasche hängt seitlich am Körper.':'Die Hände hängen seitlich neben dem Körper.'} Durch das Lächeln wirkt die Person freundlich.`;}
function solutions(){return `${head('Lösungen · Übungen')}<h3>1 · Genau hinschauen</h3><p>T-Shirt: ${person.pattern}. Brille: ${person.glasses?'richtig':'falsch'}. Sicher sichtbar: die lange Hose. Weitere Merkmale beispielsweise: ${person.style}e Haare, ${person.face}es Gesicht.</p><h3>2 · Treffende Wörter</h3><p>Schulterlange Haare; lockig; ein blaues, gestreiftes T-Shirt. Freie Wortgruppen: z. B. ein rundes, schmales Gesicht; kurze, braune Haare; ein weiter, gestreifter Pullover. Andere passende Lösungen gelten ebenfalls.</p><h3>3 · Ordnung schaffen</h3><p>Zuordnung: A, B, C, D, E, C. Reihenfolge: 4, 1, 5, 3, 2. Eine klare Ordnung hilft, sich die Person Schritt für Schritt vorzustellen.</p><h3>4 · Besser formulieren</h3><p>Zum Beispiel: Alex hat kurze, braune Haare. Auffällig ist die Brille. Gegenwart: Mika trägt eine graue Hose.</p><h3>5 · Textdetektiv</h3><p>Nora ist elf Jahre alt, hat glatte Haare und trägt ein gepunktetes T-Shirt. Die Aussage über ihren Charakter ist unbegründet und wird gestrichen.</p><div class="hint">Die Schreibaufgabe hat viele richtige Lösungen. Entscheidend sind Genauigkeit, Gliederung und ein verständlicher zusammenhängender Text.</div>`;}
function modelSolution(){const text=sample(person);return `${head('Lösungen · Beispieltext')}${card(person)}<h3>Eine mögliche Beschreibung (${text.split(/\s+/).length} Wörter)</h3><p class="quote">${text}</p><p>Der Text ist ein Beispiel, keine Vorlage zum Auswendiglernen. Eigene treffende Formulierungen sind erwünscht.</p><h3>Rückmeldung zur Schreibaufgabe</h3><ul><li>Stimmen die Angaben mit der Vorlage überein?</li><li>Kann man sich die Person anhand des Textes vorstellen?</li><li>Sind die Merkmale sinnvoll geordnet?</li><li>Ist der Eindruck als Eindruck formuliert?</li><li>Was gelingt schon gut, was kann genauer werden?</li></ul>`;}
function sheet(content,number=''){return `<section class="sheet">${content}${number?`<div class="page-number">${number}</div>`:''}</section>`;}
function exercisePages(){return [observation(),vocabulary(),ordering(),head('4 & 5 · Sprache unter der Lupe')+phrasing()+detective()];}
function content(){if(active===0)return observation();if(active===1)return vocabulary();if(active===2)return ordering();if(active===3)return phrasing();if(active===4)return detective();return '';}
function syncURL(){try{const u=new URL(location.href);u.searchParams.set('person',person.seed);history.replaceState(null,'',u);}catch{ /* Printing also works in restricted embeds. */ }}
function render(){document.body.classList.toggle('mono',document.querySelector('#mono').checked);document.querySelector('#person-status').textContent=`Vorlage ${person.seed} · ${person.name} · ${person.age} Jahre · ${person.height} cm. Die Adresse merkt sich diese Person.`;document.querySelector('#navigation').innerHTML=stationNames.map((n,i)=>`<button data-station="${i}" ${i===active?'aria-current="step"':''}>${n}</button>`).join('');document.querySelector('#screen-content').innerHTML=active===5?sheet(writingFront())+sheet(writingBack()):active===6?sheet(solutions())+sheet(modelSolution()):sheet(content());document.querySelectorAll('.help').forEach(e=>e.hidden=document.querySelector('#level').value!=='help');syncURL();preparePrint();}
function preparePrint(variants=false){const scope=document.querySelector('#print-scope').value;let pages=[];if(variants){const saved=person;const batch=[saved,makePerson(newSeed()),makePerson(newSeed())];batch.forEach(p=>{person=p;pages.push(writingFront(p),writingBack());});person=saved;}else if(scope==='solutions')pages=[solutions(),modelSolution()];else if(scope==='writing')pages=[writingFront(),writingBack()];else if(scope==='exercises')pages=exercisePages();else if(scope==='current')pages=active===5?[writingFront(),writingBack()]:active===6?[solutions(),modelSolution()]:[active<3?content():head('Sprache unter der Lupe')+content()];else pages=[...exercisePages(),writingFront(),writingBack()];const root=document.querySelector('#print-root');root.classList.toggle('no-help',document.querySelector('#level').value!=='help');root.innerHTML=pages.map((p,i)=>sheet(p,`${i+1} / ${pages.length}`)).join('');root.querySelectorAll('.screen-only,details,.feedback,.choices').forEach(e=>e.remove());root.querySelectorAll('.help').forEach(e=>e.hidden=document.querySelector('#level').value!=='help');}
document.querySelector('#generate').addEventListener('click',()=>{person=makePerson(newSeed());render();});
document.querySelector('#navigation').addEventListener('click',e=>{const b=e.target.closest('[data-station]');if(b){active=Number(b.dataset.station);render();}});
document.querySelector('#screen-content').addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b){const f=b.closest('fieldset'),out=f.querySelector('.feedback'),ok=b.dataset.choice===f.dataset.answer;out.textContent=(ok?'Richtig! ':'Noch nicht. ')+out.dataset.explanation;out.classList.toggle('wrong',!ok);}if(e.target.id==='check-sorting'){const answers=[...document.querySelectorAll('#screen-content .sort-answer')];const count=answers.filter(a=>a.value===a.dataset.answer).length;document.querySelector('#sorting-feedback').textContent=`${count} von ${answers.length} richtig. `+(count===answers.length?'Alle Merkmale sind passend zugeordnet.':'Prüfe die Zuordnung noch einmal. Eine Brille zählt hier zu den Besonderheiten.');}});
document.querySelector('#level').addEventListener('change',render);
document.querySelector('#mono').addEventListener('change',render);
document.querySelector('#print-scope').addEventListener('change',()=>preparePrint());
let printingVariants=false;
document.querySelector('#print').addEventListener('click',()=>{preparePrint();window.print();});
document.querySelector('#variants').addEventListener('click',()=>{printingVariants=true;preparePrint(true);window.print();});
window.addEventListener('beforeprint',()=>{if(!printingVariants)preparePrint();});
window.addEventListener('afterprint',()=>{printingVariants=false;preparePrint();});
render();
