/* All artwork and exercises are local. A seed keeps screen, solutions and print in sync. */
'use strict';
const names = ['Alex','Mika','Lena','Noah','Samira','Emil','Mara','Jona','Elif','Robin','Nora','Theo'];
const colors = [{name:'blau',hex:'#5486b5'},{name:'grün',hex:'#6b956b'},{name:'rot',hex:'#c56b60'},{name:'gelb',hex:'#e7bc52'}];
const hairColors = [{name:'braun',hex:'#71503a'},{name:'blond',hex:'#dfbd70'},{name:'schwarz',hex:'#303338'},{name:'rotbraun',hex:'#ab603b'}];
function random(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function makePerson(seed){const r=random(seed),pick=a=>a[Math.floor(r()*a.length)];return {seed,name:pick(names),age:10+Math.floor(r()*4),height:140+Math.floor(r()*23),hair:pick(hairColors),style:pick(['kurz','schulterlang','lockig']),face:pick(['oval','rund']),shirt:pick(colors),pattern:pick(['gestreift','gepunktet']),glasses:r()>.5,freckles:r()>.5,skin:pick(['#f3d2b6','#d8a47f','#aa7355']),build:pick(['schmal','kräftig']),bag:r()>.5};}
function newSeed(){return crypto.getRandomValues(new Uint32Array(1))[0];}
const initialSeed=new URLSearchParams(location.search).get('person');
let person=makePerson(/^\d{1,10}$/.test(initialSeed||'')?Number(initialSeed)>>>0:newSeed());
let active=0;
const stationNames=['1 · Beobachten','2 · Präzisieren','3 · Strukturieren','4 · Formulieren','5 · Überarbeiten','Schreibblatt','Lösungen'];
let illustrationId=0;
function art(p){
 const patternId=`pattern-${p.seed}-${++illustrationId}`;
 const width=p.build==='kräftig'?50:41;
 const hairBack=p.style==='schulterlang'?`<path d="M78 78 Q72 19 120 23 Q167 23 164 83 L172 150 L69 150Z" fill="${p.hair.hex}"/>`:'';
 const hair=p.style==='lockig'?Array.from({length:9},(_,i)=>`<circle cx="${79+i*10}" cy="${47-Math.sin(i/8*Math.PI)*18}" r="14" fill="${p.hair.hex}"/>`).join(''):`<path d="M79 64 Q73 22 117 25 Q165 19 162 66 Q145 55 139 39 Q114 63 79 64Z" fill="${p.hair.hex}"/>`;
 const pattern=p.pattern==='gestreift'?'<path d="M0 5H12" stroke="#303d3b" stroke-width="2"/>':'<circle cx="5" cy="5" r="2" fill="#303d3b"/>';
 return `<svg class="person-art" viewBox="0 0 240 390" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Gezeichnete Person als Vorlage für die Beschreibung"><defs><pattern id="${patternId}" width="12" height="12" patternUnits="userSpaceOnUse">${pattern}</pattern></defs><g stroke="#303d3b" stroke-width="2" stroke-linejoin="round">${hairBack}<path d="M91 239 L116 238 L115 350 L88 350Z M124 238 L151 239 L155 350 L127 350Z" fill="#d9dce0"/><path d="M87 345H115V366H70Q66 351 87 345 M127 345H155L170 361V366H127Z" fill="#fafafa"/><path d="M${120-width} 142 L${108-width} 226 Q${109-width} 244 ${121-width} 240 L${135-width} 169 M${120+width} 142 L${132+width} 226 Q${131+width} 244 ${119+width} 240 L${105+width} 169" fill="${p.skin}"/><path d="M108 108V136H132V108" fill="${p.skin}"/><path d="M108 129 L${120-width} 140 L${107-width} 180 L${125-width} 188 L${128-width} 239 H${112+width} L${115+width} 188 L${133+width} 180 L${120+width} 140 L132 129 Q120 148 108 129Z" fill="${p.shirt.hex}"/><path d="M108 129 L${120-width} 140 L${107-width} 180 L${125-width} 188 L${128-width} 239 H${112+width} L${115+width} 188 L${133+width} 180 L${120+width} 140 L132 129 Q120 148 108 129Z" fill="url(#${patternId})"/><ellipse cx="79" cy="79" rx="7" ry="11" fill="${p.skin}"/><ellipse cx="161" cy="79" rx="7" ry="11" fill="${p.skin}"/><ellipse cx="120" cy="77" rx="${p.face==='rund'?42:35}" ry="45" fill="${p.skin}"/>${hair}<path d="M96 67L107 65 M134 65L145 67" fill="none"/><circle cx="103" cy="77" r="3"/><circle cx="137" cy="77" r="3"/><path d="M119 79L115 92H122 M108 102Q120 110 132 102" fill="none"/>${p.freckles?'<g fill="#825239" stroke="none"><circle cx="95" cy="90" r="1.8"/><circle cx="102" cy="93" r="1.8"/><circle cx="97" cy="97" r="1.8"/><circle cx="142" cy="91" r="1.8"/><circle cx="148" cy="95" r="1.8"/><circle cx="140" cy="97" r="1.8"/></g>':''}${p.glasses?'<g fill="none" stroke-width="3"><rect x="88" y="68" width="27" height="20" rx="7"/><rect x="125" y="68" width="27" height="20" rx="7"/><path d="M115 75H125 M80 73L88 75 M152 75L161 73"/></g>':''}${p.bag?'<path d="M87 140L159 226" fill="none" stroke="#795e45" stroke-width="8"/><rect x="144" y="211" width="37" height="45" rx="5" fill="#c8ab83"/><path d="M145 224H180"/>':''}</g></svg>`;
}
function lines(n=2){return `<div class="lines ${n>4?'large':n===1?'short':''}">${'<span></span>'.repeat(n)}</div>`;}
function head(title,id){return `<div class="sheet-head"><span>Deutsch · 5. Schulstufe</span><span>Personenbeschreibung · Vorlage ${person.seed}</span></div><h2>${title}</h2><div class="name-line">Name: ____________________________ Klasse: ______ Datum: __________</div>`;}
function card(p){return `<div class="portrait-layout">${art(p)}<div class="person-card"><span class="tag">Deine Schreibvorlage</span><h3>${p.name}</h3><div class="facts"><span>${p.age} Jahre</span><span>${p.height} cm groß</span></div><p>Beschreibe so genau, dass jemand die Person wiedererkennen kann.</p><p class="small">Alle Figuren sind erfunden. Name, Alter und Größe stehen fest. Weitere Angaben entnimmst du dem Bild.</p><p class="print-only">Farbangaben für Schwarz-Weiß-Kopien: Haare ${p.hair.name}; T-Shirt ${p.shirt.name}; Hose grau; Schuhe weiß.</p></div></div>`;}
function quiz(id,q,options,correct,why){return `<fieldset data-answer="${correct}"><legend>${q}</legend><div class="choices">${options.map((o,i)=>`<button class="choice" data-choice="${i}" aria-describedby="feedback-${id}">${o}</button>`).join('')}</div><div class="print-only print-choices">${options.map(o=>'□ '+o).join(' &nbsp; ')}</div><p class="feedback" id="feedback-${id}" data-explanation="${why}" role="status"></p></fieldset>`;}
function observation(){return `${head('1 · Beobachten und belegen')}${card(person)}<p>Unterscheide sichtbare Merkmale, Angaben der Infokarte und Vermutungen.</p>${quiz('fact','Welche Aussage ist durch das Bild belegt?',['Die Person ist sportlich, weil sie Turnschuhe trägt.','Die Person trägt eine lange, graue Hose.','Die Person ist elf Jahre alt.'],1,'Die Hose ist sichtbar. Alter kommt aus der Infokarte. Kleidung beweist keine sportlichen Fähigkeiten.')}<div class="task"><strong>Notiere drei Merkmale, an denen du diese Person wiedererkennst. Ordne sie nach ihrer Bedeutung und begründe deine erste Wahl.</strong>${lines(3)}</div><div class="task"><strong>„Die Person ist freundlich.“ Formuliere vorsichtiger und nenne einen sichtbaren Beleg.</strong>${lines(2)}</div><details><summary>Begründung vergleichen</summary><p>„Durch den lächelnden Mund wirkt die Person freundlich.“ Das beschreibt einen Eindruck. Ob sie tatsächlich freundlich handelt, wissen wir nicht. Markante Merkmale sind meist hilfreicher als Selbstverständlichkeiten wie „hat eine Nase“.</p></details>`;}
function vocabulary(){return `${head('2 · Präzise statt beliebig')}<p>Wähle Wörter nach ihrer Bedeutung. Eine längere Formulierung ist nicht automatisch genauer.</p>${quiz('word1','Welche Wortgruppe ergänzt Länge, Farbe und Form, ohne eine Angabe zu wiederholen?',['lange, schöne, tolle Haare','schulterlange, kastanienbraune, glatte Haare','kurze, nicht lange, eher kurze Haare'],1,'Länge, Farbe und Form liefern drei verschiedene Informationen. „Schön“ ist eine Bewertung.')}<div class="task"><strong>Ersetze ungenaue Angaben durch überprüfbare Merkmale.</strong><p>„coole Kleidung“ → Kleidungsstück + Farbe + Muster</p>${lines(1)}<p>„besondere Haare“ → Länge + Farbe + Form</p>${lines(1)}</div><div class="wordbank help">Wortschatz: oval · rundlich · schmal · kräftig gebaut · schulterlang · gelockt · einfarbig · längs / quer gestreift · rechteckiges Brillengestell</div><div class="task"><strong>Welche Angaben gehören zusammen? Erkläre den Bedeutungsunterschied.</strong><p>schmal / klein &nbsp; · &nbsp; lockig / schulterlang &nbsp; · &nbsp; gemustert / gepunktet</p>${lines(3)}</div><div class="task"><strong>Beschreibe zwei Merkmale deiner Figur besonders genau. Verwende nur Wörter, die zum Bild passen.</strong>${lines(2)}</div><details><summary>Lösungsimpuls</summary><p>„Schmal“ beschreibt die Breite bzw. den Körperbau, „klein“ die Größe. Haarform und Haarlänge sind verschiedene Merkmale. „Gepunktet“ bezeichnet ein bestimmtes Muster und ist genauer als „gemustert“.</p></details>`;}
function ordering(){return `${head('3 · Einen Text sinnvoll aufbauen')}<p>Die Sätze gehören zu einer anderen Beispielperson. Ordne sie zu einer Beschreibung. Schreibe die Buchstaben in deiner Reihenfolge auf.</p><div class="quote"><p><strong>A</strong> Zum dunkelgrünen Pullover trägt sie eine schwarze Hose und weiße Turnschuhe.</p><p><strong>B</strong> Besonders auffällig ist eine schmale Narbe über ihrer linken Augenbraue.</p><p><strong>C</strong> Elif ist elf Jahre alt und 150 cm groß.</p><p><strong>D</strong> Ihr ovales Gesicht wird von schulterlangen, glatten Haaren eingerahmt.</p><p><strong>E</strong> Sie hat einen schmalen Körperbau und steht aufrecht.</p></div>${lines(1)}<div class="task"><strong>Begründe deine Reihenfolge. Wo beginnt ein neuer Beschreibungsbereich?</strong>${lines(3)}</div><div class="task"><strong>Eine Mitschülerin beginnt mit der auffälligen Narbe. Kann auch das sinnvoll sein? Begründe.</strong>${lines(2)}</div><div class="hint help">Vom Gesamteindruck zu Einzelheiten: allgemeine Angaben → Körperbau → Kopf → Kleidung → Besonderheit. Vermeide unnötige Sprünge.</div><details><summary>Reihenfolge vergleichen</summary><p>C – E – D – A – B ist eine schlüssige Möglichkeit. Auch C – E – D – B – A passt, weil die Narbe zum Gesicht gehört. Eine auffällige Besonderheit am Anfang kann beim Wiedererkennen helfen. Entscheidend ist eine nachvollziehbare Ordnung.</p></details>`;}
function phrasing(){return `${head('4 · Sätze verbinden und variieren')}<p>Überarbeite diesen Text. Bewahre alle Informationen, vermeide Wiederholungen und bleibe sachlich.</p><div class="quote">Robin ist elf Jahre alt. Robin ist 149 cm groß. Robin hat ein ovales Gesicht. Robin hat kurze Haare. Die Haare sind braun. Robin hat eine rechteckige Brille. Robin trägt ein blaues T-Shirt. Das T-Shirt ist gestreift.</div><div class="task"><strong>Schreibe daraus drei bis vier flüssige Sätze. Beginne höchstens einen Satz mit „Robin“. Nutze einmal einen Relativsatz, zum Beispiel mit „das“.</strong>${lines(5)}</div><div class="wordbank help">Verbinde zusammengehörige Angaben. Mögliche Verben: einrahmen · reichen bis · tragen · auffallen. Ein Relativsatz erklärt ein Nomen genauer: „Das T-Shirt, das …, …“</div>${quiz('tense','Welche Fassung ist sprachlich korrekt und sachlich?',['Die Brille, die rechteckig ist, sitzt vor den Augen.','Die Brille die rechteckig ist sitzt vor den Augen.','Die rechteckige Brille beweist, dass Robin klug ist.'],0,'Der eingeschobene Relativsatz wird durch zwei Kommas abgetrennt. Eine Brille beweist keine Klugheit.')}<div class="task"><strong>Verbessere: „Gestern trug Robin eine Hose und hat ein schönes Oberteil.“ Beschreibe im Präsens. Erfinde keine fehlenden Farben oder Muster.</strong>${lines(2)}</div><details><summary>Eine mögliche Überarbeitung</summary><p>Robin ist elf Jahre alt und 149 cm groß. Kurze, braune Haare rahmen das ovale Gesicht ein. Vor den Augen sitzt eine rechteckige Brille. Das T-Shirt, das Robin trägt, ist blau und gestreift.</p><p>Präsens: „Robin trägt eine Hose und ein Oberteil.“ Für eine genauere Beschreibung fehlen Angaben. „Schön“ ist eine persönliche Bewertung.</p></details>`;}
function detective(){return `${head('5 · Prüfen und überarbeiten')}<div class="hint"><strong>Verlässliche Angaben:</strong> Nora, 11 Jahre, 148 cm, glatte schulterlange Haare, gepunktetes T-Shirt, rechteckige Brille. Weitere Angaben liegen nicht vor.</div><div class="quote">Nora ist zwölf Jahre alt und 148 cm groß. Ihre Haare waren lockig und reichen bis zu den Schultern. Sie trägt ein gestreiftes T-Shirt. Die rechteckige Brille zeigt, dass sie besonders fleißig ist. Das modische Oberteil steht ihr super. Nora hat grüne Augen.</div><div class="task"><strong>Finde sieben problematische Stellen. Unterscheide falsche Angaben, unbelegte Behauptungen, Wertungen und einen Zeitformfehler.</strong>${lines(4)}</div><div class="task"><strong>Schreibe eine sachliche, widerspruchsfreie Fassung. Behalte alle verlässlichen Informationen und ordne sie sinnvoll.</strong>${lines(5)}</div><details><summary>Fehler mit Begründungen</summary><p>1. zwölf → elf. 2. waren → sind (Präsens). 3. lockig → glatt. 4. gestreift → gepunktet. 5. „fleißig“ ist nicht aus der Brille ableitbar. 6. „modisch … steht ihr super“ ist eine persönliche Wertung. 7. Grüne Augen sind nicht belegt.</p><p>Nora ist elf Jahre alt und 148 cm groß. Ihre glatten Haare reichen bis zu den Schultern. Sie trägt eine rechteckige Brille und ein gepunktetes T-Shirt.</p></details>`;}
function writingFront(p=person){return `${head('Schreibwerkstatt · Beobachten & planen')}${card(p)}<div class="hint"><strong>Dein Auftrag:</strong> Beschreibe ${p.name} so, dass ein anderes Kind die Figur unter ähnlichen Bildern erkennen könnte. Schreibe etwa <strong>140 bis 180 Wörter</strong> im Präsens. Genauigkeit zählt mehr als Länge. Erfinde keine Angaben.</div><div class="plan">${['Allgemeine Angaben und Körperbau','Haare und Gesicht','Kleidung: Farbe, Form, Muster','Auffällige Merkmale und ihre Lage'].map(s=>`<div><strong>${s}</strong>${lines(2)}</div>`).join('')}</div><p><strong>Sprachziel:</strong> Verbinde passende Angaben, variiere Satzanfänge und verwende mindestens einen sinnvoll eingebauten Relativsatz. Kennzeichne einen Eindruck und belege ihn am Bild.</p><p class="small">Plane drei Absätze. Vermeide Füllsätze über selbstverständliche Körperteile. Schreibe auf der Rückseite, bei Bedarf auf einem Zusatzblatt.</p><div class="wordbank help small">von … eingerahmt · reicht bis … · vor den Augen · auf den Wangen · dazu trägt … · seitlich hängt … · durch … wirkt …</div>`;}
function writingBack(){return `${head('Schreibwerkstatt · Schreiben & prüfen')}<p><strong>Meine Personenbeschreibung · etwa 140 bis 180 Wörter</strong></p>${lines(20)}<p class="small"><strong>Prüfen:</strong> □ Angaben belegt □ sinnvoll geordnet □ genaue Wortwahl □ abwechslungsreiche Sätze □ Präsens und Kommas □ Eindruck begründet</p><p class="small"><strong>Überarbeiten:</strong> Unterstreiche deinen treffendsten Satz. Verbessere anschließend eine ungenaue oder holprige Stelle.</p>`;}
function sample(p){return `${p.name} ist ${p.age} Jahre alt und ${p.height} Zentimeter groß. Die Person hat einen ${p.build==='schmal'?'schmalen':'kräftigen'} Körperbau und steht aufrecht mit den Armen seitlich am Körper.\n\nDas ${p.face==='oval'?'ovale':'runde'} Gesicht wird von ${p.hair.name==='braun'?'braunen':p.hair.name==='blond'?'blonden':p.hair.name==='schwarz'?'schwarzen':'rotbraunen'} Haaren eingerahmt. ${p.style==='schulterlang'?'Die Haare reichen ungefähr bis zu den Schultern.':p.style==='lockig'?'Über der Stirn und an den Seiten bilden die Haare deutlich erkennbare Locken.':'Die kurz geschnittenen Haare lassen die Ohren und den Hals gut erkennen.'} ${p.glasses?'Vor den Augen sitzt eine dunkle Brille, deren rechteckige Gläser abgerundete Ecken haben.':'Über den Augen sind zwei schmale, dunkle Augenbrauen zu erkennen.'} ${p.freckles?'Auf beiden Wangen fallen mehrere kleine Sommersprossen auf.':'Unter der Nase ist ein leicht nach oben gebogener Mund zu sehen.'}\n\nDas ${p.shirt.name==='blau'?'blaue':p.shirt.name==='grün'?'grüne':p.shirt.name==='rot'?'rote':'gelbe'} T-Shirt, das ${p.name} trägt, ist ${p.pattern}. ${p.pattern==='gestreift'?'Die dunklen Streifen verlaufen waagrecht und sind über das ganze Oberteil verteilt.':'Die kleinen, dunklen Punkte sind in regelmäßigen Abständen über das Oberteil verteilt.'} Seine kurzen Ärmel enden oberhalb der Ellbogen, sodass die Unterarme frei bleiben. Dazu trägt die Person eine lange, graue Hose und weiße Schuhe mit dunklen Umrissen. Die Hosenbeine reichen bis zu den Schuhen. ${p.bag?'Seitlich hängt eine kleine, bräunliche Umhängetasche mit einem langen Riemen, der schräg über das T-Shirt verläuft.':'Besonders gut lässt sich die Person an der Kombination aus Haarform, Gesichtsform und dem gemusterten T-Shirt wiedererkennen.'} Durch den lächelnden Mund wirkt ${p.name} freundlich. Über den tatsächlichen Charakter sagt dieser Gesichtsausdruck jedoch nichts Sicheres aus.`;}
function solutions(){return `${head('Lösungen · Begründen statt raten')}<h3>1 · Beobachten</h3><p>Sicher sichtbar: lange, graue Hose. Weitere Merkmale: ${person.style==='kurz'?'kurze':person.style==='lockig'?'lockige':'schulterlange'} Haare, ${person.face==='oval'?'ovales':'rundes'} Gesicht, ${person.pattern==='gestreift'?'gestreiftes':'gepunktetes'} T-Shirt. Ein Lächeln kann freundlich wirken, beweist aber keinen Charakterzug. Begründete Gewichtungen sind individuell.</p><h3>2 · Wortschatz</h3><p>Schulterlange, kastanienbraune, glatte Haare. „Schmal“ betrifft den Körperbau, „klein“ die Größe. „Lockig“ ist eine Form, „schulterlang“ eine Länge. „Gepunktet“ ist genauer als „gemustert“. Freie Antworten müssen überprüfbare Angaben liefern.</p><h3>3 · Aufbau</h3><p>C – E – D – A – B oder C – E – D – B – A. Die zweite Variante beschreibt die Narbe beim Gesicht. Andere schlüssig begründete Reihenfolgen sind möglich.</p><h3>4 · Sprache</h3><p>Robin ist elf Jahre alt und 149 cm groß. Kurze, braune Haare rahmen das ovale Gesicht ein. Vor den Augen sitzt eine rechteckige Brille. Das T-Shirt, das Robin trägt, ist blau und gestreift.</p><p>Kommafrage: erste Antwort. Präsens: „Robin trägt eine Hose und ein Oberteil.“ Keine Farben erfinden.</p><h3>5 · Textprüfung</h3><p>Sieben Stellen: zwölf → elf; waren → sind; lockig → glatt; gestreift → gepunktet; Fleiß unbelegt; Modeurteil subjektiv; Augenfarbe unbelegt. Schulterlänge, Größe und rechteckige Brille bleiben erhalten.</p><div class="hint">Freie Texte brauchen eine inhaltliche Rückmeldung. Die Wortzahl allein sagt nichts über ihre Qualität aus.</div>`;}
function modelSolution(){const text=sample(person);return `${head('Lösungen · Beispieltext')}${card(person)}<h3>Eine mögliche Beschreibung (${text.split(/\s+/).length} Wörter)</h3><div class="quote">${text.split('\n\n').map(paragraph=>`<p>${paragraph}</p>`).join('')}</div><p>Der Text ist ein Beispiel, keine Vorlage zum Auswendiglernen. Eigene treffende Formulierungen sind erwünscht.</p><h3>Rückmeldung zur Schreibaufgabe</h3><ul><li>Stimmen die Angaben mit der Vorlage überein?</li><li>Kann man sich die Person anhand des Textes vorstellen?</li><li>Sind die Merkmale sinnvoll geordnet?</li><li>Ist der Eindruck als Eindruck formuliert?</li><li>Was gelingt schon gut, was kann genauer werden?</li></ul>`;}
function sheet(content,number=''){return `<section class="sheet">${content}${number?`<div class="page-number">${number}</div>`:''}</section>`;}
function exercisePages(){return [observation(),vocabulary(),ordering(),phrasing(),detective()];}
function content(){if(active===0)return observation();if(active===1)return vocabulary();if(active===2)return ordering();if(active===3)return phrasing();if(active===4)return detective();return '';}
function syncURL(){try{const u=new URL(location.href);u.searchParams.set('person',person.seed);history.replaceState(null,'',u);}catch{ /* Printing also works in restricted embeds. */ }}
function render(){document.body.classList.toggle('mono',document.querySelector('#mono').checked);document.querySelector('#person-status').textContent=`Vorlage ${person.seed} · ${person.name} · ${person.age} Jahre · ${person.height} cm. Die Adresse merkt sich diese Person.`;document.querySelector('#navigation').innerHTML=stationNames.map((n,i)=>`<button data-station="${i}" ${i===active?'aria-current="step"':''}>${n}</button>`).join('');document.querySelector('#screen-content').innerHTML=active===5?sheet(writingFront())+sheet(writingBack()):active===6?sheet(solutions())+sheet(modelSolution()):sheet(content());document.querySelectorAll('.help').forEach(e=>e.hidden=document.querySelector('#level').value!=='help');syncURL();preparePrint();}
function preparePrint(variants=false){const scope=document.querySelector('#print-scope').value;let pages=[];if(variants){const saved=person;const batch=[saved,makePerson(newSeed()),makePerson(newSeed())];batch.forEach(p=>{person=p;pages.push(writingFront(p),writingBack());});person=saved;}else if(scope==='solutions')pages=[solutions(),modelSolution()];else if(scope==='writing')pages=[writingFront(),writingBack()];else if(scope==='exercises')pages=exercisePages();else if(scope==='current')pages=active===5?[writingFront(),writingBack()]:active===6?[solutions(),modelSolution()]:[active<3?content():content()];else pages=[...exercisePages(),writingFront(),writingBack()];const root=document.querySelector('#print-root');root.classList.toggle('no-help',document.querySelector('#level').value!=='help');root.innerHTML=pages.map((p,i)=>sheet(p,`${i+1} / ${pages.length}`)).join('');root.querySelectorAll('.screen-only,details,.feedback,.choices').forEach(e=>e.remove());root.querySelectorAll('.help').forEach(e=>e.hidden=document.querySelector('#level').value!=='help');}
document.querySelector('#generate').addEventListener('click',()=>{person=makePerson(newSeed());render();});
document.querySelector('#navigation').addEventListener('click',e=>{const b=e.target.closest('[data-station]');if(b){active=Number(b.dataset.station);render();}});
document.querySelector('#screen-content').addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(b){const f=b.closest('fieldset'),out=f.querySelector('.feedback'),ok=b.dataset.choice===f.dataset.answer;out.textContent=(ok?'Richtig! ':'Noch nicht. ')+out.dataset.explanation;out.classList.toggle('wrong',!ok);}});
document.querySelector('#level').addEventListener('change',render);
document.querySelector('#mono').addEventListener('change',render);
document.querySelector('#print-scope').addEventListener('change',()=>preparePrint());
let printingVariants=false;
document.querySelector('#print').addEventListener('click',()=>{preparePrint();window.print();});
document.querySelector('#variants').addEventListener('click',()=>{printingVariants=true;preparePrint(true);window.print();});
window.addEventListener('beforeprint',()=>{if(!printingVariants)preparePrint();});
window.addEventListener('afterprint',()=>{printingVariants=false;preparePrint();});
render();
